version: 2
meta:
  name: ctrend-x
  display_name: CTREND-X
  category: ML 앙상블 (GradientBoosting)
  timeframe: 1D
  short_mode: FULL
  status: RETIRED
  created_at: '2026-02-20'
  retired_at: '2026-02-22'
  economic_rationale: CTREND의 ElasticNet을 GradientBoosting으로 교체하여 비선형 feature 상호작용
    캡처. 동일 28개 기술적 지표 사용, 트리 기반 모델로 변수간 interaction 자동 학습.
  rationale_references: []
  rationale_category: null
parameters:
  training_window: 160
  prediction_horizon: 4
  n_estimators: 415
  max_depth: 3
  learning_rate: 0.419572578449225
  subsample: 0.8
  vol_target: 0.35
  vol_window: 73
phases:
  P1:
    status: PASS
    date: '2026-02-20'
    details:
      score: 24
      max_score: 30
  P2:
    status: PASS
    date: '2026-02-20'
    details:
      note: 4-file 구조 구현 완료 (config/preprocessor/signal/strategy + tests 4파일). Registry
        등록.
  P3:
    status: PASS
    date: '2026-02-20'
    details:
      C1: PASS
      C2: PASS
      C3: PASS
      C4: PASS
      C5: PASS
      C6: PASS
      C7: PASS
      warnings: 1.0
  P4:
    status: PASS
    date: '2026-02-20'
    details:
      sharpe: 4.15
      cagr: 321.9
      mdd: 22.2
      trades: 466.0
      oos_sharpe: 2.98
      decay: 34.8
  P5:
    status: PASS
    date: '2026-02-21'
    details:
      param_verdicts:
        training_window: PASS
        prediction_horizon: PASS
        n_estimators: PASS
        max_depth: PASS
        learning_rate: PASS
        vol_window: PASS
asset_performance:
- symbol: SOL/USDT
  sharpe: 4.15
  cagr: 321.9
  mdd: 22.2
  trades: 466
  profit_factor: 2.46
- symbol: BNB/USDT
  sharpe: 4.06
  cagr: 333.2
  mdd: 17.4
  trades: 449
  profit_factor: 4.54
- symbol: ETH/USDT
  sharpe: 4.01
  cagr: 285.4
  mdd: 16.8
  trades: 470
  profit_factor: 3.45
- symbol: BTC/USDT
  sharpe: 3.76
  cagr: 251.2
  mdd: 20.5
  trades: 467
  profit_factor: 4.26
- symbol: DOGE/USDT
  sharpe: 3.3
  cagr: 317.4
  mdd: 18.8
  trades: 478
  profit_factor: 5.89
decisions:
- date: '2026-02-20'
  phase: P1
  verdict: PASS
  rationale: 24/30점. CTREND 확장판으로 비선형 상호작용 캡처 기대.
- date: '2026-02-20'
  phase: P2
  verdict: PASS
  rationale: 구현 완료. ruff/pyright 0 errors. 199 tests passed (5 strategies).
- date: '2026-02-20'
  phase: P3
  verdict: PASS
  rationale: 'C1-C7 전항목 PASS. CTREND compute_all_features 재사용 — 기존 승인 코드. ML rolling
    fit도 CTREND 동일 패턴. W-HEDGE: HEDGE_ONLY가 DISABLED와 동일 처리. Warning 1건'
- date: '2026-02-20'
  phase: P4
  verdict: PASS
  rationale: 'P4A SOL Sharpe 4.15, CAGR +321.9%, MDD 22.2%. P4B IS/OOS PASS: OOS Sharpe
    2.98, Decay 34.8%'
- date: '2026-02-20'
  phase: P5
  verdict: PASS
  rationale: IS Sharpe 4.56→5.17 (+13.2%), OOS=3.23
- date: '2026-02-21'
  phase: P5
  verdict: PASS
  rationale: 'PASS: all stable'
