version: 2
meta:
  name: gbtrend
  display_name: GBTrend
  category: ML 앙상블 (Momentum GradientBoosting)
  timeframe: 1D
  short_mode: FULL
  status: TESTING
  created_at: '2026-02-20'
  economic_rationale: 모멘텀 중심 12개 feature를 GradientBoosting으로 결합. CTREND(28 feat) 대비
    feature 축소 + 모멘텀 특화로 상관도 차별화. ROC 4종, EMA Cross 2종, RSI, ADX, ATR Ratio, Vol Ratio,
    Momentum 2종.
  rationale_references: []
  rationale_category: null
parameters:
  training_window: 195
  prediction_horizon: 3
  n_estimators: 345
  max_depth: 4
  learning_rate: 0.06189707918754463
  subsample: 0.8
  vol_target: 0.35
  vol_window: 102
phases:
  P1:
    status: PASS
    date: '2026-02-20'
    details:
      score: 22
      max_score: 30
  P2:
    status: PASS
    date: '2026-02-20'
    details:
      note: 4-file 구조 구현 완료 (config/preprocessor/signal/strategy + tests 4파일). Registry
        등록.
  P3:
    status: PASS
    date: '2026-02-20'
    details:
      C1: PASS
      C2: PASS
      C3: PASS
      C4: PASS
      C5: PASS
      C6: PASS
      C7: PASS
      warnings: 1.0
  P4:
    status: PASS
    date: '2026-02-20'
    details:
      sharpe: 4.18
      cagr: 325.3
      mdd: 17.3
      trades: 497.0
      oos_sharpe: 3.8
      decay: 10.2
asset_performance:
- symbol: ETH/USDT
  sharpe: 4.18
  cagr: 325.3
  mdd: 17.3
  trades: 497
  profit_factor: 3.99
- symbol: SOL/USDT
  sharpe: 4.1
  cagr: 322.5
  mdd: 23.6
  trades: 453
  profit_factor: 3.83
- symbol: BTC/USDT
  sharpe: 3.6
  cagr: 242.6
  mdd: 23.0
  trades: 487
  profit_factor: 3.93
- symbol: BNB/USDT
  sharpe: 3.16
  cagr: 223.9
  mdd: 18.5
  trades: 495
  profit_factor: 2.56
- symbol: DOGE/USDT
  sharpe: 2.79
  cagr: 226.4
  mdd: 38.3
  trades: 495
  profit_factor: 4.6
decisions:
- date: '2026-02-20'
  phase: P1
  verdict: PASS
  rationale: 22/30점. 모멘텀 특화 feature로 CTREND 대비 low correlation 앙상블 가치.
- date: '2026-02-20'
  phase: P2
  verdict: PASS
  rationale: 구현 완료. ruff/pyright 0 errors. 199 tests passed (5 strategies).
- date: '2026-02-20'
  phase: P3
  verdict: PASS
  rationale: 'C1-C7 전항목 PASS. ML rolling fit은 CTREND 승인 패턴과 동일. W-HEDGE: HEDGE_ONLY가
    DISABLED와 동일 처리. Warning 1건'
- date: '2026-02-20'
  phase: P4
  verdict: PASS
  rationale: 'P4A ETH Sharpe 4.18, CAGR +325.3%, MDD 17.3%. P4B IS/OOS PASS: OOS Sharpe
    3.80, Decay 10.2% (우수)'
- date: '2026-02-20'
  phase: P5
  verdict: PASS
  rationale: IS Sharpe 4.23→4.31 (+1.9%), OOS=3.73
