"""Core data models using Pydantic for validation."""

from datetime import datetime
from decimal import Decimal
from enum import Enum

from pydantic import BaseModel, Field


class SignalType(str, Enum):
    """Trading signal types."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class OrderSide(str, Enum):
    """Order side."""

    BUY = "BUY"
    SELL = "SELL"


class OrderType(str, Enum):
    """Order types."""

    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP_LOSS = "STOP_LOSS"
    TAKE_PROFIT = "TAKE_PROFIT"


class OrderStatus(str, Enum):
    """Order status."""

    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class Candle(BaseModel):
    """OHLCV candle data."""

    symbol: str
    timeframe: str
    timestamp: datetime
    open: Decimal
    high: Decimal
    low: Decimal
    close: Decimal
    volume: Decimal

    class Config:
        frozen = True


class Signal(BaseModel):
    """Trading signal generated by strategy."""

    strategy_name: str
    symbol: str
    signal_type: SignalType
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    strength: float = Field(default=1.0, ge=0.0, le=1.0)  # Signal confidence
    metadata: dict = Field(default_factory=dict)  # Additional info from strategy


class OrderRequest(BaseModel):
    """Order request from Portfolio Manager."""

    symbol: str
    side: OrderSide
    quantity: Decimal
    order_type: OrderType = OrderType.MARKET
    price: Decimal | None = None  # For limit orders
    stop_price: Decimal | None = None  # For stop orders
    signal: Signal  # Original signal reference
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class Order(BaseModel):
    """Order approved by Risk Manager."""

    id: str  # Internal order ID
    client_order_id: str  # For idempotency
    symbol: str
    side: OrderSide
    order_type: OrderType
    quantity: Decimal
    price: Decimal | None = None
    stop_price: Decimal | None = None
    status: OrderStatus = OrderStatus.PENDING
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class Fill(BaseModel):
    """Order fill/execution report."""

    order_id: str
    exchange_order_id: str
    symbol: str
    side: OrderSide
    quantity: Decimal
    price: Decimal
    commission: Decimal = Decimal("0")
    commission_asset: str = "USDT"
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class Position(BaseModel):
    """Current position for a symbol."""

    symbol: str
    quantity: Decimal = Decimal("0")
    entry_price: Decimal = Decimal("0")
    current_price: Decimal = Decimal("0")
    unrealized_pnl: Decimal = Decimal("0")
    realized_pnl: Decimal = Decimal("0")
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    @property
    def is_open(self) -> bool:
        """Check if position is open."""
        return self.quantity != Decimal("0")

    @property
    def side(self) -> OrderSide | None:
        """Get position side."""
        if self.quantity > 0:
            return OrderSide.BUY
        if self.quantity < 0:
            return OrderSide.SELL
        return None
